Vagrant.configure(2) do |config|
  config.vm.box = "CentOS7"
  config.vm.box_url = 'https://github.com/holms/vagrant-centos7-box/releases/download/7.1.1503.001/CentOS-7.1.1503-x86_64-netboot.box'
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.vm.synced_folder "../../dev_1/", "/home/vagrant/dev", create: true, owner: "vagrant", group: "vagrant"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision :shell, path: "install-ansible.sh"
  config.vm.provision :ansible_local do |ansible|
    ansible.playbook = 'playbook.yml'
  end
end
